version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "Github Action Dependencies"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    target-branch: "develop"
    labels:
      - dependencies
